services:
  currency-exchange-api:
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - API_URL=https://v6.exchangerate-api.com/v6/ab979c01aaac59fa64ac5247/latest/USD
      - API_KEY=ab979c01aaac59fa64ac5247
    restart: unless-stopped
